import { prisma } from '../config/database';
import { mlClient } from '../integrations/ml/ml.client';
import { logger } from '../config/logger';

// ── Known Skills Dictionary & Canonical Normalization ────────────────────────
const CANONICAL_SKILLS: Record<string, string> = {
  javascript: 'JavaScript',
  js: 'JavaScript',
  typescript: 'TypeScript',
  ts: 'TypeScript',
  python: 'Python',
  py: 'Python',
  'react.js': 'React',
  reactjs: 'React',
  react: 'React',
  'node.js': 'Node.js',
  nodejs: 'Node.js',
  node: 'Node.js',
  'angular.js': 'Angular',
  angularjs: 'Angular',
  angular: 'Angular',
  'vue.js': 'Vue.js',
  vuejs: 'Vue.js',
  vue: 'Vue.js',
  'next.js': 'Next.js',
  nextjs: 'Next.js',
  next: 'Next.js',
  html: 'HTML',
  html5: 'HTML',
  css: 'CSS',
  css3: 'CSS',
  sass: 'Sass',
  scss: 'Sass',
  tailwind: 'Tailwind CSS',
  tailwindcss: 'Tailwind CSS',
  django: 'Django',
  flask: 'Flask',
  fastapi: 'FastAPI',
  express: 'Express.js',
  expressjs: 'Express.js',
  sql: 'SQL',
  postgresql: 'PostgreSQL',
  postgres: 'PostgreSQL',
  mysql: 'MySQL',
  sqlite: 'SQLite',
  mongodb: 'MongoDB',
  mongo: 'MongoDB',
  redis: 'Redis',
  prisma: 'Prisma ORM',
  typeorm: 'TypeORM',
  sequelize: 'Sequelize',
  graphql: 'GraphQL',
  'restful apis': 'RESTful APIs',
  rest: 'RESTful APIs',
  'rest api': 'RESTful APIs',
  docker: 'Docker',
  kubernetes: 'Kubernetes',
  k8s: 'Kubernetes',
  aws: 'AWS',
  azure: 'Azure',
  gcp: 'Google Cloud Platform',
  git: 'Git',
  github: 'GitHub',
  gitlab: 'GitLab',
  'ci/cd': 'CI/CD',
  cicd: 'CI/CD',
  linux: 'Linux',
  bash: 'Bash',
  java: 'Java',
  spring: 'Spring Boot',
  springboot: 'Spring Boot',
  'c#': 'C#',
  csharp: 'C#',
  dotnet: '.NET',
  '.net': '.NET',
  cpp: 'C++',
  'c++': 'C++',
  golang: 'Go',
  go: 'Go',
  rust: 'Rust',
  php: 'PHP',
  laravel: 'Laravel',
  ruby: 'Ruby',
  rails: 'Ruby on Rails',
  'agile/scrum': 'Agile / Scrum',
  agile: 'Agile / Scrum',
  scrum: 'Agile / Scrum',
  jira: 'Jira',
  figma: 'Figma',
  jest: 'Jest',
  cypress: 'Cypress',
  playwright: 'Playwright',
  pytorch: 'PyTorch',
  tensorflow: 'TensorFlow',
  scikit: 'scikit-learn',
  nlp: 'Natural Language Processing (NLP)',
  'machine learning': 'Machine Learning',
  ml: 'Machine Learning',
  pandas: 'Pandas',
  numpy: 'NumPy',
};

// ── Degree Keyword Matchers ──────────────────────────────────────────────────
const DEGREE_PATTERNS = [
  /\b(bachelor(?:\s+of\s+[a-zA-Z\s]+)?|bachelors?|b\.?sc?\.?|bsc\.?|b\.?s\.?|b\.?a\.?|b\.?eng\.?|b\.?tech\.?|bca|b\.?c\.?a\.?|undergraduate|degree\s+in)\b/i,
  /\b(master(?:\s+of\s+[a-zA-Z\s]+)?|masters?|m\.?sc?\.?|msc\.?|m\.?s\.?|m\.?a\.?|m\.?eng\.?|m\.?tech\.?|mba|m\.?b\.?a\.?|postgraduate)\b/i,
  /\b(ph\.?d\.?|doctorate|doctoral|doctor\s+of\s+[a-zA-Z\s]+)\b/i,
  /\b(associate(?:\s+degree)?|diploma|higher\s+diploma|certificate|certification)\b/i,
];



export const resumeParserService = new ResumeParserService();
